Convert samples to use shared_ptr stream creation interface
google/oboe pull request #1016
Opened 2020-09-17 19:59 UTC by ggfan

This is for github issue https://github.com/google/oboe/issues/830, please kindly take a look, thank you!

2020-09-17 23:11 UTC, philburk requested changes

2020-09-17 23:11 UTC, philburk commented on samples/RhythmGame/src/main/cpp/Game.cpp
> +    if (mAudioStream){
To be safe, call stop() before close().

2020-09-17 23:11 UTC, philburk commented on samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp
> +        mAudioStream->close();
mAudioStream.reset();

2020-09-18 19:35 UTC, ggfan commented on samples/RhythmGame/src/main/cpp/Game.cpp
>      }
added.

2020-09-18 19:39 UTC, ggfan commented on samples/MegaDrone/src/main/cpp/MegaDroneEngine.h
> +    std::shared_ptr<AudioStream> mStream;
It seems that restart() is only called from ErrorAfterClose() callback, in which case the stream is already closed., so restart() could assume that stream is in closed state.

the above does not solve the destructor case; wondering we could do: 
  - destructor: stop and close stream if it is NOT closed yet; ( we do not have to call mStream->reset() here as it is going away
 - that mirrors the creation inside constructor.

WDYT?

2020-09-18 19:39 UTC, ggfan commented on samples/RhythmGame/src/main/cpp/Game.cpp
> +    if (mAudioStream){
done

2020-09-18 19:39 UTC, ggfan commented on samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp
> +        mAudioStream->close();
done

2020-09-21 16:11 UTC, dturner commented on samples/MegaDrone/src/main/cpp/MegaDroneEngine.h
> +    std::shared_ptr<AudioStream> mStream;
@philburk Why shouldn't `MegaDroneEngine` call `start()` in its constructor? It doesn't make much sense (to me) to have the engine object without a running playback stream.

2020-09-22 17:55 UTC, ggfan commented on samples/LiveEffect/src/main/cpp/LiveEffectEngine.h
> +using SharedStream = std::shared_ptr<oboe::AudioStream>;
done

2020-09-22 20:03 UTC, dturner approved these changes
LGTM but it'd be good to get Phil's view on the outstanding question around MegaDrone starting a stream inside the constructor.

2020-09-23 21:11 UTC, philburk requested changes

2020-09-23 21:11 UTC, philburk commented on samples/MegaDrone/src/main/cpp/MegaDroneEngine.h
> +    void stop(void);
void not needed

2020-09-23 21:17 UTC, philburk approved these changes

2020-09-23 21:26 UTC, merged