[Drumthumper] Code improvements
google/oboe pull request #1031
Opened 2020-10-01 03:22 UTC by antonioolf

Applying code improvements suggested by Android Studio

- Use of setter method instead of property access syntax;
- Make some methods private;
- Convert concatenation to template ;
- Removed unused variables and parameters;
- Updated the libraries `androidx.appcompat:appcompat` and `androidx.core:core-ktx` to the last versions.

Successfully tested on Android Studio 4.0.1

2020-10-02 19:04 UTC, philburk requested changes
Thanks for the cleanup. A few minor nits.

2020-10-02 19:04 UTC, philburk commented on samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/TriggerPad.kt
> +        return TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, mTextSizeSp, resources.displayMetrics)
long line

2020-10-02 19:04 UTC, philburk commented on samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/TriggerPad.kt
> +       /* var padLeft = getPaddingLeft() */
We can probably just remove these.

2020-10-02 20:34 UTC, antonioolf commented on samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/DrumThumperActivity.kt
> +        findViewById<Button>(R.id.mixCtrlBtn).text = if (mMixControlsShowing) "Hide Mix Controls" else "Show Mix Controls"
done

2020-10-02 20:34 UTC, antonioolf commented on samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/TriggerPad.kt
> +        return TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, mTextSizeSp, resources.displayMetrics)
done

2020-10-02 20:35 UTC, antonioolf commented on samples/drumthumper/src/main/java/com/plausibleaudio/drumthumper/TriggerPad.kt
> +       /* var padLeft = getPaddingLeft() */
done

2020-10-02 20:36 UTC, antonioolf commented
@philburk  Thank you very much for your attention and code review.
I just submitted the corrections. Feel free to request me if there is anything else.

2020-10-02 23:09 UTC, philburk commented
Looks good. I assume the vars were changed to val because val is "final".
When Paul approves we can merge this.

2020-10-02 23:10 UTC, philburk approved these changes
I am OK if Paul is OK. It's his code.

2020-10-05 16:56 UTC, android-usb commented
I'm OK with it.

2020-10-05 16:56 UTC, merged

2020-10-05 19:01 UTC, antonioolf commented
@philburk and @android-usb Thank you! :smile: