Fix CalculateLatencyInMillisReturnsClosedIfSupported test
google/oboe pull request #1319
Opened 2021-06-28 22:03 UTC by robertwu1

AudioStreamAAudio::calculateLatencyMillis calls getTimestamp which returns Result::ErrorInvalidState when the stream is not open. CalculateLatencyInMillisReturnsClosedIfSupported explicitly checks for Result::ErrorClosed.

There are 3 "fixes"
1. Consider Result::ErrorInvalidState to be the correct error code when we query latency. This one seems ok but overall it doesn't sound very intuitive. The upside is that we don't cause existing apps to break.
2. Make calculateLatencyMillis return ErrorClosed when there is no audio stream.
3. Make getTimestamp return Result::ErrorClosed instead.

I did option 2 in this PR but I open to the other options as well

Fixes #1297

Tested with UnitTestRunner

2021-06-28 23:26 UTC, philburk requested changes
Let's keep the behavior in calculateLatencyMillis() because it can still return ErrorInvalidState due to a race condition if closed after this null test.
Better to test for ErrorInvalidState or just != Result::OK.

2021-06-29 00:22 UTC, robertwu1 commented
> Let's keep the behavior in calculateLatencyMillis() because it can still return ErrorInvalidState due to a race condition if closed after this null test.
> Better to test for ErrorInvalidState or just != Result::OK.

Done in iterations 2/3!

2021-06-29 10:44 UTC, dturner commented
The problem with returning `ErrorInvalidState` instead of `ErrorClosed` is that it breaks convention. If you call `setBufferSizeInFrames`, `waitForStateChange`, `requestStart` or many other methods when the stream is closed you'll get `ErrorClosed`. 

I suggest that we return `ErrorClosed` when the stream is closed, and `ErrorInvalidState` when the stream is in any other state except STARTED.

2021-06-29 16:10 UTC, robertwu1 commented
> The problem with returning `ErrorInvalidState` instead of `ErrorClosed` is that it breaks convention. If you call `setBufferSizeInFrames`, `waitForStateChange`, `requestStart` or many other methods when the stream is closed you'll get `ErrorClosed`.
> 
> I suggest that we return `ErrorClosed` when the stream is closed, and `ErrorInvalidState` when the stream is in any other state except STARTED.

We agree that this is the goal but option 2 (https://github.com/google/oboe/pull/1319/commits/4a82d9a3f43156c166ec523e54aead78f0cfb2b4) introduces a race condition. This first checks that we can get an mAAudioStream handle, then whether the stream is open, then checking the mAAudioStream. Phil and I have discussed that "fixing" the unittests is the main priority and we can try to unify the return error codes at a different time

2021-06-29 17:19 UTC, philburk commented
> I suggest that we return ErrorClosed when the stream is closed, and ErrorInvalidState when the
> stream is in any other state except STARTED.

I agree with that for a later PR. Let's fix the test as a high priority and then review and cleanup the error return codes next. That may require or adding or changing some tests as well.

2021-06-29 17:19 UTC, philburk approved these changes

2021-06-29 17:20 UTC, philburk commented
@robertwu1 - if you merge this, make sure to squash the 3 commits.

2021-06-29 17:25 UTC, merged