Add setPackageName and setAttributionTag to the Oboe builder
google/oboe pull request #1332
Opened 2021-07-08 21:16 UTC by robertwu1

In Android 12, we added an ability to set Package Names and Attribution Tags to AAudio. We are also doing this in Oboe.
Note that getting the values comes from the context (Context#getPackageName()/Context#getAttributionTag())

Fixes #1282

Tested via:
Built OboeTester

2021-07-09 18:41 UTC, robertwu1 commented
It seems like certain types of streams don't play well with setting the package name. For example, Tap To Tone Latency works perfectly but Glitch Test has some weird bugs. When running the unit tests, some randomly fail setting the package name before 
 commit 4. @philburk should I assign a bug to Phillip Moltmann?

2021-07-13 19:47 UTC, philburk requested changes

2021-07-13 19:47 UTC, philburk commented on src/aaudio/AudioStreamAAudio.cpp
> +    //if (mLibLoader->stream_getPackageName != nullptr) {
Remove dead code.

2021-07-13 20:34 UTC, robertwu1 commented on include/oboe/AudioStreamBase.h
> +    std::string getPackageName() const { return mPackageName; }
Thanks Phil!

2021-07-13 20:35 UTC, robertwu1 commented
@philburk Thanks for adding comments! I removed all of the setters. Let me know if this looks good

2021-07-14 16:48 UTC, dturner commented
These features were added to AAudio to allow more detailed logging.

2021-07-14 16:56 UTC, philburk approved these changes

2021-07-14 16:56 UTC, merged