(LiveEffect) Disable setting playback or recording devices with OpenSL ES
google/oboe pull request #1424
Opened 2021-10-19 20:29 UTC by robertwu1

Fixes #1419

Also slightly restructured the UI to have API selection on top. See how the playback/recording device selection is now disabled when OpenES SL is selected.

![Screenshot_20211019-132151](https://user-images.githubusercontent.com/85952307/137985547-79846b9f-a101-4af9-a803-e4d1cd8fa3b7.png)

2021-10-30 00:31 UTC, philburk requested changes
I tested this on Nougat MR1 SDK 25.
It defaults to using OpenSL ES.
So I expected the device menus to be disabled.
But actually they were enabled.

2021-11-01 17:13 UTC, robertwu1 commented
Thanks for testing this. I fixed the issues you encountered in the second commit. Can you retry this when you get a chance?

2021-11-01 23:40 UTC, philburk commented
I am still seeing the problem with these latest changes.

REPRODUCE
Launch LiveEffect on emulator running Android 25.
Click on the "Recording Device: menu.

EXPECT: menu should NOT pop up

ACTUAL: menu pops up and offers device choices

If I START then STOP the test then the "Recording Devices" menu is properly disabled.

![Screen Shot 2021-11-01 at 4 38 28 PM](https://user-images.githubusercontent.com/5175913/139756317-1b233dcb-5842-4529-bf3b-1daf8f15c493.png)

2021-11-01 23:54 UTC, robertwu1 commented
Now this should work. I tested with an Android emulator running Android 25.

2021-11-07 00:29 UTC, philburk approved these changes

2021-11-08 17:37 UTC, merged