Add more info for setFramesPerDataCallback
google/oboe pull request #1426
Opened 2021-10-25 22:12 UTC by robertwu1

Fixes #1326

2021-10-30 00:33 UTC, philburk requested changes

2021-10-30 00:33 UTC, philburk commented on include/oboe/AudioStreamBuilder.h
> +     * This just collects the data into a the number of frames that you app requires.
"your app"

2021-11-01 17:12 UTC, robertwu1 commented on include/oboe/AudioStreamBuilder.h
> +     * This just collects the data into a the number of frames that you app requires.
Thanks!

2021-11-01 23:42 UTC, philburk approved these changes

2021-11-01 23:43 UTC, merged