OboeTester: Add input device selector to Tap To Tone
google/oboe pull request #1830
Opened 2023-06-16 16:40 UTC by robertwu1

Fixes #470

2023-06-18 01:34 UTC, philburk reviewed
Thanks for doing this. The intention was to just find the built-in mic and select it.
Is there an advantage in giving the user an option to pick the input from a menu?
Does it default to Built-in Mic type?

2023-06-20 18:21 UTC, robertwu1 commented
> Thanks for doing this. The intention was to just find the built-in mic and select it. Is there an advantage in giving the user an option to pick the input from a menu? Does it default to Built-in Mic type?

I was testing the PR on a Pixel 6 and it has two built-in MICs. That's why I wanted to surface all audio sources.

2023-06-27 15:33 UTC, philburk requested changes

2023-06-27 15:34 UTC, philburk commented
> I was testing the PR on a Pixel 6 and it has two built-in MICs. That's why I wanted to surface all audio sources.

OK.

2023-06-28 22:52 UTC, philburk approved these changes

2023-06-28 22:54 UTC, merged