Added logging to deprecated functions
google/oboe pull request #1926
Opened 2023-10-03 20:21 UTC by JP-Lisn

As discussed in https://github.com/google/oboe/issues/1925, logging when using deprecated functions has been added. I did waffle on if these should be warnings or debug messages... I landed warnings. I Will change if a different log level is preferred. 

FYI - Just signed the CLA.

2023-10-06 21:04 UTC, philburk approved these changes
Thanks for doing this!

2023-10-06 21:05 UTC, philburk commented
Warnings are good because use of the functions can lead to crashes.

2023-10-06 21:13 UTC, JP-Lisn commented
Whoops, let me double check this.

2023-10-06 21:26 UTC, philburk requested changes
CI caught build errors. Did you get build errors when you tested this?

You need to:

#include "common/OboeDebug.h"

But that might interfere with making the pre-built.
We normally only do logging in .cpp files.

2023-10-06 21:26 UTC, philburk commented on include/oboe/AudioStreamBuilder.h
> +        LOGW("`setCallback` is deprecated, Call setDataCallback(std::shared_ptr<AudioStreamDataCallback>) and
Needs a " at the end of 521 and a " and space at the beginning of line 521

2023-10-06 21:53 UTC, JP-Lisn commented
Sorry about that, a little embarrassing 😞 I did run the build script, but I must have accidentally done so from the wrong source directory.

2023-10-06 22:55 UTC, JP-Lisn commented
Interesting, 

Both the `build_all_android.sh` and `prefab_build.sh` complete successfully when run locally.

2023-10-07 20:11 UTC, philburk requested changes
Moving the OboeDebug.h file is an API change that could break existing application builds.
We will need to discuss this internally and decide how to move forward.
Please hold off on any more changes. Thanks.

2023-10-07 22:13 UTC, JP-Lisn commented
Totally understand. Initially, I thought this change was all good until I built the sample applications. Tests and build scripts all worked. The only way I could solve this without code repetition was to expose that header publicly so the linker could find it. I have run all the samples and tests and found nothing that broke thus far with this change.  

I didn't think this would cause issues with existing builds, as the header was not exposed before. I assumed only internal library references would be at issue, although I realize I might be missing something here. 

If Internally you decide on a different path, I would be happy to assist in making that happen :) 
Thanks again for all your help.

2023-10-11 18:40 UTC, JP-Lisn commented
Closing, for now replaced with: https://github.com/google/oboe/pull/1930

2023-10-11 18:40 UTC, closed without merging