OboeTester: Create foreground service
google/oboe pull request #2071
Opened 2024-07-11 22:11 UTC by robertwu1

Fixes #2065

2024-07-11 22:45 UTC, atneya approved these changes
lgtm

2024-07-11 22:57 UTC, philburk requested changes
For testing and debugging, we need to retain the ability to test what happens if you do NOT start a ForegroundService. So please add another checkbox on MainActivity screen below "enable background operation" labelled "use foregroundService".

2024-07-11 22:57 UTC, philburk commented on apps/OboeTester/app/src/main/java/com/mobileer/oboetester/MainActivity.java
> +import static com.mobileer.oboetester.AudioForegroundService.ACTION_START;
Are these used?

2024-07-11 22:57 UTC, philburk commented on apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioForegroundService.java
> +    private static final String TAG = "AudioForegroundService";
I have been using OboeTester as the tag so I can enable all OboeTester logs.

2024-07-12 00:49 UTC, philburk approved these changes
What notification does the user see?

2024-07-12 18:15 UTC, robertwu1 commented
![Screenshot_20240712-110941~2](https://github.com/user-attachments/assets/0dd218bf-62e4-4f3e-a566-c632ff746b84)
![Screenshot_20240712-110951](https://github.com/user-attachments/assets/77f7180d-f213-47e5-83f1-201648f660f5)

2024-07-12 18:16 UTC, merged